「Open62541を使用したOPC-UAクライアント開発」記事の追加
mamezou-tech/mamezou-tech-site pull request #1041
Opened 2024-01-29 03:30 UTC by hayat0-ota

@masayuki-kono @shuji-morimoto @kazuki-ogawa 

前回記事「Open62541を使用したOPC-UAクライアント開発」に引き続き、そのクライアント版を作成しました。
前回と同じく「ロボット」セクション内に記事を追加しました。

レビューをお願いいたします。

2024-01-29 05:00 UTC, shuji-morimoto commented
ソースコードはできれば横スクロールなしで読めるようにしてほしいです。

void readSampleVariable(UA_Client* client) {
    UA_Int32 value = 0;
    UA_Variant* var = UA_Variant_new();

でvarのメモリ解放は必要ないのでしょうか？(自動で解放される？)


「おわりに」では「本記事の目的」と同じことを書いている部分は不要かと思います。
自分なりの感想や注意事項やその他伝えたい内容を記載すると良いかと思います。

2024-01-29 11:42 UTC, masayuki-kono requested changes
レビューしました。

2024-01-29 11:42 UTC, masayuki-kono commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +詳細は[こちら](https://nanamasuhoshi.hatenadiary.org/entry/20150902/1441181518)をご覧ください。
HatenaBlogのリンクが張られていますが使用例が簡単に記述されているのみで「詳細」として紹介するには適切ではないように思います。robocopyのコマンドについて解説したMSの公式ページのリンクにして下さい。

2024-01-29 11:42 UTC, masayuki-kono commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +プロジェクト名: SimpleServer
クライアントのサンプルコードなのに、プロジェクト名がSimpleClientではなく、SimpleServerというのは違和感があります。
（見直すのが大変ならそのままでも良いです）

2024-01-29 14:55 UTC, kazuki-ogawa reviewed
レビューしました！

2024-01-29 14:55 UTC, kazuki-ogawa commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +本記事を読む前にをご覧ください。
typo

2024-01-29 14:55 UTC, kazuki-ogawa commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +  - CMake 3.25.0-rc2
統一するなら「本記事では-使用しています」

2024-01-29 14:55 UTC, kazuki-ogawa commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +# プロジェクトの作成と設定（前回記事と同様）
見出しの括弧の内容と後述の「ちなみに〜」の内容が重複するので
:::infoを使うと良さそう（好みなので採用はおまかせです）

2024-01-30 11:02 UTC, hayat0-ota commented
@masayuki-kono @shuji-morimoto @kazuki-ogawa 
ご指摘いただいた内容について修正を行いました。
ありがとうございました。

2024-01-30 11:06 UTC, hayat0-ota commented
@kondoumh
「ロボット」ページ内に記事「Open62541を使用したOPC-UAクライアント開発」を作成し、先行してロボットグループ内で頂いたレビューを反映しました。
こちらの記事についてレビューをお願いできますでしょうか。

2024-01-30 11:22 UTC, kondoumh requested changes
レビューしました。

deno-lint.lock / deno.lock についてはプロジェクト全体に影響するので PR に含めないよう revert お願いします。

2024-01-30 11:22 UTC, kondoumh commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +date: 2024-01-28
公開日付を1/30以降にしてください。

2024-01-30 11:22 UTC, kondoumh commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +本記事で実装するコードはこちら[^1]にも記載しています。
脚注番号1は既出なので2ですね。なので、以降の脚注番号が1個ずつずれます。

ちなみに、脚注書式は Markdown の末尾に書かずに文の途中に書いても脚注としてレンダリングされます。

2024-01-30 11:24 UTC, kondoumh commented on src/posts/robotics/opcua/opcua_open62541_client.md
> +autor: hayato-ota
タイポしてます。`author` にしてください。

2024-01-31 01:03 UTC, hayat0-ota commented
@kondoumh 
レビュー有難うございます。ご指摘いただいた点＋αを修正しました。

2024-01-31 01:16 UTC, kondoumh approved these changes
LGTM

2024-01-31 01:17 UTC, merged