Feature/robotics/240315 manip
mamezou-tech/mamezou-tech-site pull request #1110
Opened 2024-03-15 08:53 UTC by Takahiro-ISHII-M

第２弾ロボットアルゴです。校正お願いします。

2024-03-18 09:33 UTC, kondoumh reviewed
レビューしました。

- 日付が古いので他の方のレビューが完了したら更新をお願いします。
- AI が提案しているイラストも問題なければ追加してください。

シリーズなので、ナビゲーションを追加してはいかがでしょうか。
記事の末尾に以下のように表示されます。

![](https://i.gyazo.com/47f7e8ddca7df483e197551a64419409.png)

ヘッダーで以下のように `prevPage` タグを書くと前回記事を指定できます。

```markdown
---
title: ロボットマニピュレータ制御のアルゴリズム2
author: takahiro-ishii
date: 2024-03-15
prevPage: ./src/posts/robotics/manip-algo/manip-algo.md
---
```

また前回記事のヘッダーで以下のように `nextPage` タグを追加すれば前回記事からリンクされます。

```markdown
---
title: ロボットマニピュレータ制御のアルゴリズム
author: takahiro-ishii
date: 2023-12-01
nextPage: ./src/posts/robotics/manip-algo/manip-algo2.md
---

```

2024-03-18 09:33 UTC, kondoumh commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +今回は、前回説明した基礎的な軌跡生成処理アルゴリズムの詳細の一例を紹介する。具体的にはユーザが指定した特徴的な位置と姿勢からどう補間して軌跡（位置と姿勢のセット）のサンプルを算出するか、について言及する。
`前回説明した基礎的な軌跡生成処理アルゴリズム` の部分に、前回記事のリンクを追加してはいかがでしょうか。

2024-03-18 22:07 UTC, masayuki-kono requested changes
レビューしました。よろしくお願いいたします。

2024-03-18 22:07 UTC, masayuki-kono commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +3の点以上KP、いいかえれば連続で2区間以上が指定されるとき区分3次スプライン補間による滑らかな位置の3次元軌跡を得ることができる。
> 3の点以上KP

「3点以上のKP」の誤記

2024-03-18 22:07 UTC, masayuki-kono commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +	const REAL qw =m_quat1;
= の前後にスペースを設けるか否かをサンプルコード内で統一して下さい。

2024-03-18 22:07 UTC, masayuki-kono commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +このときパラメータtを0から1まで変化させながら、$\bold q$を漸次サンプルすれば、滑らかなQuaternion列が求まる。これを区間m-1の大円円弧のうち$\bold q_{[m-1]}～\bold q_{[m-1]1}$部分と区間mの大円円弧のうち$\bold q_{[m]2}～\bold q_{[m+1]}$部分とを合わせて滑らかな姿勢の軌跡とする。
> q_{[m-1]}～\bold q_{[m-1]1}$部分

「q_{[m-1]}～\bold q_{[m]1}$部分」の誤記でしょうか？

2024-03-19 06:45 UTC, Takahiro-ISHII-M commented
修正しました。

2024-03-19 06:49 UTC, masayuki-kono approved these changes
修正頂いた内容を確認致しました。追加指摘は御座いません。LGTMです。

2024-03-19 06:56 UTC, Takahiro-ISHII-M commented
お手数をおかけします。ありがとうございました。
LGTMって何？

2024-03-19 07:20 UTC, masayuki-kono commented
> お手数をおかけします。ありがとうございました。 LGTMって何？

https://knowyourmeme.com/memes/lgtm
の抜粋の和訳を以下へ記します。

LGTMは「Looks Good To Me」の頭字語で、主にプログラマーがソフトウェア製品のレビュー プロセス中に 1 つの承認または好意的なフィードバックを表現するために使用します。このスラング用語は、早くも 2000 年代中頃から後半にかけて開発者によって使用されてきたと考えられていますが、2010 年代初頭にはオンライン コーディング コミュニティ、特にコード リポジトリ ホスティング サービス Github の一般用語になりました。

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +ここでKPも、前回述べたツール先端の位置・姿勢の定義を使い同様に表現する。ここでKPの軌跡上の順番の番号を$j$とする。（jは0以上の整数）
j-> $j$

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +& |\vec{X_j}| = |\vec{Y_j}| =|\vec{Z_j}| =1 \\
直交条件も記述した方がよいのではないでしょうか

$$ \vec{X_j} \cdot \vec{Y_j} = \vec{X_j} \cdot \vec{Z_j} = \vec{Y_j} \cdot \vec{Z_j} = 0$$

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +と表すことができる。必要なら6軸の関節角度ベクトル$\Theta_j$から$T_{KPj}$を順運動学を使って求めてもよい。また姿勢$R_{KP[j]}$はオイラー角から求めることもできる。
順運動学->逆運動学

$T_{KPj}$ -> $T_{KP[j]}$

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +$$\vec{F}(s) = (1-(s-m))*\vec{P}_{KP[m]} + (s-m)*\vec{P}_{KP[m+1]}　$$
この式を見ると $s$の範囲は $m\leq s \leq m+1 (s \in \mathbb{R})$だと思います。
前行を見ると、$s>0$となっていますが、上記の範囲の方が適切ではないでしょうか？
そもそも以下のような式ではだめなのですか？

$$ \vec{F}(s) = (1-s)*\vec{P} _{KP[m]} + s *\vec{P} _{KP[m+1]} \quad (0 < s< 1)$$

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +$$ m=floor(s)$$
$floor$ -> $\rm{floor}$ （`\rm{floor}`）

関数はローマン体を使うべきです。

2024-03-19 08:26 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +が直線補間の式となる。これをサンプリング、すなわち$s$を適当に分割して$\vec{F}(s)$を計算すれば位置の軌跡が求まる。なお、KP$_{m}$にて（s=mのとき）位置は一致するのでこの軌跡はKPを通る。
s=m -> $s=m$

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +これを下記の条件が成立するよう、任意のmにおいて連立方程式をたて、係数 $\vec{a}_m, \vec{b}_m, \vec{c}_m, \vec{d}_m$を未知数として方程式を解く。この求解は一意の計算で実行可能である。
m -> $m$

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +$$m=floor(s)$$
$floor$ -> $\rm{floor}$

関数はローマン体を使うべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +これで、UVW座標系からΣ0座標系に変換する4x4の同次行列$T^{WC}_{UV}$を算出できる。つまり、行列の回転行列部に$\vec{U},\vec{V},\vec{W}$、平行移動部に$\vec{P}_{KP[m]}$を代入する。
Σ0 -> $\Sigma_0$ （`\Sigma_0`）

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +ここで、さらに図のように$Q_c$を原点として、$Q_1$方向にu軸を置いたuv座標を規定する。UVW座標上でuvw軸はそれぞれ
座標　-> 座標系　他同様

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +R~ sin(-\theta)\\
$cos$ -> $\cos$
$sin$ -> $\sin$

関数はローマン体を使うべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +	const REAL m11=_matrix.At(0, 0), m12=_matrix.At(0, 1), m13=_matrix.At(0, 2);
REALをdoubleに統一すべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +\theta = cos^{-1}(\bold{q}_{[m]} \cdot \bold{q}_{[m+1]}) \\
$sin$ -> $\sin$ （`\cos` ）
関数はローマン体にすべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +&k_s(s)=sin((1.0-r(s)) ~ \theta)/sin(\theta) \\
$sin$ -> $\sin$ （`\sin` ）
関数はローマン体にすべきです。

数式なので1.0ではなく，1にすべきです

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +\bold{q} =Slerp(r, \bold{q}_0,\bold{q}_{1} ) \\
$Slerp$ -> $\rm{Slerp}$ （`\rm{Slerp}` ）
関数はローマン体にすべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +~ (0.0 \le r \le 1.0)
数式なので $0 \le r \le 1$とすべきです。

2024-03-19 08:27 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +& \bold q = Slerp(t, \bold q_1, \bold q_2 )　\\
$Slerp$ -> $\rm{Slerp}$ （`\rm{Slerp}` ）
関数はローマン体にすべきです。

2024-03-19 08:53 UTC, Takahiro-ISHII-M commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +と表すことができる。必要なら6軸の関節角度ベクトル$\Theta_j$から$T_{KPj}$を順運動学を使って求めてもよい。また姿勢$R_{KP[j]}$はオイラー角から求めることもできる。
「順」運動学でよいと思いますが..

2024-03-19 09:02 UTC, takehiro-toyoshima commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +と表すことができる。必要なら6軸の関節角度ベクトル$\Theta_j$から$T_{KPj}$を順運動学を使って求めてもよい。また姿勢$R_{KP[j]}$はオイラー角から求めることもできる。
すみません、順運動学でよいです。
読み間違えました。

2024-03-19 09:07 UTC, Takahiro-ISHII-M commented on src/posts/robotics/manip-algo2/manip-algo2.md
> +$$\vec{F}(s) = (1-(s-m))*\vec{P}_{KP[m]} + (s-m)*\vec{P}_{KP[m+1]}　$$
その通りですが、sを時刻のように扱いたかったので「0=s<1」に限定しませんでした。そのときのF(s)の表現がこのようになりました。プログラムでも多分こんな風にしてるはずです。豊島さんもちゃんと正しく理解されているし、このままとさせていただきます。

2024-03-19 10:11 UTC, Takahiro-ISHII-M commented
takehiro-toyoshimaさん
Reviewありがとうございました。修正しました。

2024-03-21 00:36 UTC, kondoumh commented
> takehiro-toyoshimaさん Reviewありがとうございました。修正しました。

@takehiro-toyoshima @Takahiro-ISHII-M `@` をつけるとメンションになって通知が飛びますよ。
レビュー完了したら教えてください。

2024-03-21 04:44 UTC, Takahiro-ISHII-M commented
@kondoumh さん、ご情報ありがとうございます。
ではあらためまして、
@takehiro-toyoshimaさん
Reviewありがとうございました。豊島さんの校正に対してすべて修正したつもりですが、どうでしょうか？

2024-03-22 08:49 UTC, takehiro-toyoshima commented
@Takahiro-ISHII-M 
ご対応ありがとうございました。LGTMです。

2024-03-22 08:50 UTC, takehiro-toyoshima approved these changes

2024-03-22 21:01 UTC, masayuki-kono commented
@Takahiro-ISHII-M 
以下のコメントの通り、ヘッダの日付（公開日）が古いので更新をお願いいたします。
https://github.com/mamezou-tech/mamezou-tech-site/pull/1110#pullrequestreview-1942347782

2024-03-25 00:32 UTC, Takahiro-ISHII-M commented
@kondoumh さん
@takehiro-toyoshimaさん
@masayuki-kono さん
ご指摘ありがとうございました。
日付更新しました。

2024-03-25 01:38 UTC, merged

2024-03-25 09:32 UTC, Takahiro-ISHII-M commented
@kondoumh さん：
　　　cc: @takehiro-toyoshimaさん
　　　      @masayuki-kono さん
すいません。main merge後で恐縮なのですが、公開された自分の記事を確認してて
TYPOを自分で見つけちゃいました。
---
<<< ### 球面線形補間（\rm{Slerp}）
>>> ### 球面線形補間（$\rm{Slerp}$）
---
さきほど修正しました。
大変お手数ですが再マージできませんか?

2024-03-25 10:00 UTC, kondoumh commented
> ## @kondoumh さん：
> 　　　cc: @takehiro-toyoshimaさん
> 　　　 @masayuki-kono さん
> すいません。main merge後で恐縮なのですが、公開された自分の記事を確認してて
> TYPOを自分で見つけちゃいました。
> <<< ### 球面線形補間（\rm{Slerp}）
> 
> > > > ### 球面線形補間（$\rm{Slerp}$）
> 
> さきほど修正しました。 大変お手数ですが再マージできませんか?


@Takahiro-ISHII-M push しました？
タイポなど軽微な修正は main に直接 push していただいて構いませんが。

2024-03-26 07:19 UTC, Takahiro-ISHII-M commented
@kondoumh さん
　　cc: @takehiro-toyoshimaさん
　　　 @masayuki-kono さん

ご教示ありがとうございます。
修正を直接mainにpushいたしました。