Beanus紹介記事追加
mamezou-tech/mamezou-tech-site pull request #1122
Opened 2024-03-22 09:20 UTC by takehiro-toyoshima

2024-03-22 11:31 UTC, masayuki-kono requested changes
レビューしました。
2017年は懐かしすぎですね。
付加価値が高まってきている様子で良い感じです。

2024-03-22 11:31 UTC, masayuki-kono commented on src/posts/robotics/beanus/beanus_introduction.md
> +高バックドライバビリティ減速機を使うことで、高精度にトルクを推定することができます。センサレスでトルクを推定するには重力や慣性、摩擦による影響を高精度に推定する必要があります。この推定を豆蔵の技術で実現しています。
> 高バックドライバビリティ減速機を使うことで、高精度にトルクを推定することができます。
> センサレスでトルクを推定するには

「トルクを推定できる」と記載した直後に「トルクを推定するには～」だと違和感があります。
「センサレスでトルクを推定するには」を「外力を推定するには」にすると違和感はないのですが、いかがでしょうか？

2024-03-22 11:31 UTC, masayuki-kono commented on src/posts/robotics/beanus/beanus_introduction.md
> +センサレスでの力制御が難しいのは、ロボットで多く使われる波動歯車減速機は摩擦の影響が主な理由です。摩擦のモデル化が難しく、トルクを高精度に推定することが困難です。そのため、摩擦のモデル化が難しいところは、不感帯処理など摩擦の影響を無視する方策を採ることが多いです。この不感帯が大きいと小さなトルクを検出できず、力制御の性能が落ちてしまいます。一方で、高バックドライバビリティ減速機を使うことで摩擦の
> ロボットで多く使われる波動歯車減速機は摩擦の影響が主な理由です。

日本語が変です。

この節を自分なりに推敲してみました。参考までに。

センサレス力制御の実現が難しい主な理由は、ロボットに広く採用される波動歯車減速機が摩擦の影響を大きく受けることにあります。摩擦の正確なモデル化は困難であり、結果としてトルクの高精度な推定が難しいのです。多くの場合、摩擦モデルの精度が不十分な場合には、摩擦の影響を無視するようなアプローチ、例えば不感帯処理を採用します。しかし、この不感帯が大きすぎると、小さいトルクが検出できなくなり、力制御の精度が低下します。一方、高バックドライバビリティ減速機を使用すると、摩擦の影響を軽減し、不感帯を小さく保つことが可能になります。これにより、センサレスでも微細なトルクを検出でき、動画のように軽い力でロボットを動かすことができるのです。

2024-03-22 11:31 UTC, masayuki-kono commented on src/posts/robotics/beanus/beanus_introduction.md
> +三井化学の樹脂成型技術により、ロボットのフレームの大部分を樹脂化し、金属製と比べて重量を最大で1/2にまで軽くできています。金属との接合が必要な箇所には金属樹脂一体成型技術を使用し、樹脂でありながらも高い剛性を実現しました。軽量化により、衝突時の衝撃力の低減、可搬重量の増加、省電力化などが期待できます。
アームの軽量化で可搬重量って増加するんでしたっけ？
過去のポスターを見るとそのように書いてあるので、私が忘れてるだけの可能性が高いのですが。。
知ってたら教えて下さい。

2024-03-22 15:12 UTC, takehiro-toyoshima commented on src/posts/robotics/beanus/beanus_introduction.md
> +センサレスでの力制御が難しいのは、ロボットで多く使われる波動歯車減速機は摩擦の影響が主な理由です。摩擦のモデル化が難しく、トルクを高精度に推定することが困難です。そのため、摩擦のモデル化が難しいところは、不感帯処理など摩擦の影響を無視する方策を採ることが多いです。この不感帯が大きいと小さなトルクを検出できず、力制御の性能が落ちてしまいます。一方で、高バックドライバビリティ減速機を使うことで摩擦の
ご提案の内容を参考に修正しました。

2024-03-22 15:16 UTC, takehiro-toyoshima commented on src/posts/robotics/beanus/beanus_introduction.md
> +高バックドライバビリティ減速機を使うことで、高精度にトルクを推定することができます。センサレスでトルクを推定するには重力や慣性、摩擦による影響を高精度に推定する必要があります。この推定を豆蔵の技術で実現しています。
おっしゃることはわかるのですが、むしろ以下の文が不要な気がします。

>高バックドライバビリティ減速機を使うことで、高精度にトルクを推定することができます。

後の文でセンサレス力制御における高バックドライバビリティ減速機での優位性の話がでてきますし。

```
力制御を実現するためには、各関節にかかるトルクを高精度で推定することが不可欠です。
センサレスでトルクを高精度に推定するには～
```

とすると、しっくりする気がします。いかがでしょうか。

2024-03-22 15:17 UTC, takehiro-toyoshima commented on src/posts/robotics/beanus/beanus_introduction.md
> +力制御を行うには各関節に掛かるトルクを高精度に推定する必要があります。
修正しました

2024-03-22 15:21 UTC, takehiro-toyoshima commented
@masayuki-kono 

レビューありがとうございます！
指摘いただいた箇所を修正しました。ご確認お願いします。

>2017年は懐かしすぎですね。

まだ新卒2年目でした、そう考えると遥か昔のように思えます笑

2024-03-22 20:43 UTC, masayuki-kono commented on src/posts/robotics/beanus/beanus_introduction.md
> +高バックドライバビリティ減速機を使うことで、高精度にトルクを推定することができます。センサレスでトルクを推定するには重力や慣性、摩擦による影響を高精度に推定する必要があります。この推定を豆蔵の技術で実現しています。
そうですね。ご提案頂いた内容で良いと思います。

2024-03-22 20:44 UTC, masayuki-kono commented on src/posts/robotics/beanus/beanus_introduction.md
> +三井化学の樹脂成型技術により、ロボットのフレームの大部分を樹脂化し、金属製と比べて重量を最大で1/2にまで軽くできています。金属との接合が必要な箇所には金属樹脂一体成型技術を使用し、樹脂でありながらも高い剛性を実現しました。軽量化により、衝突時の衝撃力の低減、可搬重量の増加、省電力化などが期待できます。
なるほどです。有難う御座います。

2024-03-22 20:50 UTC, masayuki-kono approved these changes
LGTMです！

2024-03-22 22:42 UTC, kondoumh requested changes

2024-03-22 22:42 UTC, kondoumh commented on src/posts/robotics/beanus/beanus_introduction.md
> +date: 2023-03-22
日付が1年以上古いので、本日以降の日付に修正お願いします。

2024-03-23 07:31 UTC, takehiro-toyoshima commented on src/posts/robotics/beanus/beanus_introduction.md
> +date: 2023-03-22
@kondoumh 
本日の日付（2024/3/23）に修正しました。

2024-03-23 09:41 UTC, kondoumh approved these changes
LGTM

2024-03-23 09:41 UTC, merged