Jestの時間固定テスト
mamezou-tech/mamezou-tech-site pull request #428
Opened 2022-12-15 12:49 UTC by MameIchi

2022-12-15 13:43 UTC, kudoh commented
時間を固定するのであれば、一般的には以下のライブラリを使えばできると思うのですが、これでダメな理由を追記していただくといいと思います。

https://www.npmjs.com/package/mockdate

2022-12-15 13:43 UTC, kudoh requested changes

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    function yyyyMMddHHmmss(date: Date): string {
class 内で直接function書けないと思いますが。。

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    dateString: string;
TypeScriptだとコンパイルエラーになりませんか？
`TS2564: Property 'dateString' has no initializer and is not definitely assigned in the constructor.`

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +function hoge(date: new Date()): Hoge {
`date: new Date()`の記述は文法的に正しくないです。
書くとしたら`date: Date = new Date()`でしょうか

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    it('hogeのテスト'. () => {
`.`ではなく`,`ですね。

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        expect(result).toEqual('20221217150000');
文字列の比較であれば通常は`toEqual`ではなく、`toBe`を使います。

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    dateString: string;
あくまで例ということなのかもしれませんが、このようなものではclassを使うのは不自然な気がします。interfaceやtypeでいいのではと思います。

2022-12-15 13:43 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +tags: [advent2022, NestJS, TypeScript, Jest]
NestJSの記事ではないと思いますので、NestJSのタグは取りましょう

2022-12-15 13:44 UTC, kudoh commented
NestJSやGraphQLの記事ではないと思いますので、これに関する記述は削除した方が読者の混乱を避けられると思います。

2022-12-15 13:50 UTC, kudoh requested changes

2022-12-15 13:50 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +[公式ドキュメントのタイマーモックの方法](https://jestjs.io/ja/docs/timer-mocks)はこちら。
ちなみにこちらで引用している記事は時間固定ではなく、タイマーをモックする方法になります。
setTimeout/setIntervalを使っているコードに適用する場合の方法です。

2022-12-15 13:56 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        const result = hogeService.hoge();
HogeServiceにhogeというメソッドがないように見えます。

2022-12-15 13:56 UTC, kudoh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        const date = new Date('2022/12/17 15:00:00')
この`date`がどこでも使われていないように見えます。

2022-12-15 23:53 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    function yyyyMMddHHmmss(date: Date): string {
すみません。一旦動く形に書き直します。

2022-12-15 23:54 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    dateString: string;
typeに変更します。

2022-12-16 00:16 UTC, kondoumh reviewed
私もレビューしました。

現時点では公開が危ぶまれますね。

2022-12-16 00:16 UTC, kondoumh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +内容としては、案件で扱ったGraphQL+NestJS(+TypeScript)のテストでハマった所の紹介をしようと思います。
記事中 GraphQL っぽい箇所は全くないので、GraphQL というワードは削除した方がいいですね。

2022-12-16 00:16 UTC, kondoumh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +当時プロジェクトではNestJSを初めて扱うメンバーしかいなかったため、もっと良い方法はありそうですがこんな方法もアリだよねという事で覚書代わりに。
NestJS が初めてだからハマったのでしょうか？ もし NestJS が理由であれば、本文中でそれがわかるように書いた方がよいですね。

2022-12-16 00:16 UTC, kondoumh commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +・[非同期コードのテスト](https://jestjs.io/ja/docs/asynchronous)はawaitを使うかreturn文内に書きましょう(ググったやり方だと非同期じゃないテストを使っていて忘れがち。テストも通ってしまう。)
「ググったやり方だと非同期じゃないテストを使っていて」って何を言ってるのか分からないですね。内容については書かずに

- 非同期コードのテスト方法

だけでよいのではないかと。

2022-12-16 10:14 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    function yyyyMMddHHmmss(date: Date): string {
テストコードが動く状態に修正しました。

2022-12-16 10:14 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    dateString: string;
テストコードが動く状態に修正しました。

2022-12-16 10:15 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +function hoge(date: new Date()): Hoge {
テストコードが動く状態に修正しました。

2022-12-16 10:15 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +    it('hogeのテスト'. () => {
テストコードが動く状態に修正しました。

2022-12-16 10:16 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        expect(result).toEqual('20221217150000');
toBeで文字列比較をする形に変更しました。

2022-12-16 10:16 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +tags: [advent2022, NestJS, TypeScript, Jest]
GraphQL、NestJSに関する記述を削除しました。

2022-12-16 10:17 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +[公式ドキュメントのタイマーモックの方法](https://jestjs.io/ja/docs/timer-mocks)はこちら。
こちらの記述を削除しました。

2022-12-16 10:17 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        const result = hogeService.hoge();
テストコードが動く状態に修正しました。

2022-12-16 10:17 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +        const date = new Date('2022/12/17 15:00:00')
テストコードが動く状態に修正しました。

2022-12-16 10:17 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +内容としては、案件で扱ったGraphQL+NestJS(+TypeScript)のテストでハマった所の紹介をしようと思います。
GraphQL、NestJSに関する記述を削除しました。

2022-12-16 10:18 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +・[非同期コードのテスト](https://jestjs.io/ja/docs/asynchronous)はawaitを使うかreturn文内に書きましょう(ググったやり方だと非同期じゃないテストを使っていて忘れがち。テストも通ってしまう。)
非同期コードのテスト方法、と記述するように変更しました。

2022-12-16 10:20 UTC, MameIchi commented on src/posts/blogs/2022/1217_graphql-and-nestjs.md
> +当時プロジェクトではNestJSを初めて扱うメンバーしかいなかったため、もっと良い方法はありそうですがこんな方法もアリだよねという事で覚書代わりに。
この方法を取る原因となった、ミドルウェアが動かなかった旨に記述を変更しました。
ただ詳細な調査はされておらず、mockdateを使わなかった理由としては弱いかもしれません。

2022-12-16 10:59 UTC, kondoumh reviewed
修正確認しました。

2022-12-16 23:57 UTC, kondoumh commented
クローズします。

2022-12-16 23:57 UTC, closed without merging