IaCでのAurora PostgreSQLのメジャーバージョンアップの手順ページを追加
mamezou-tech/mamezou-tech-site pull request #774
Opened 2023-08-30 09:51 UTC by tadashi-nakamura

2023-08-30 10:27 UTC, kudoh requested changes

2023-08-30 10:27 UTC, kudoh commented on src/posts/sss/rds-major-ver-up.md
> +tags: [How to, SSS, IaC, AWS, RDS, Aurora, PostgreSQL]
How toではなく既存の`tips`でいかがでしょうか？

2023-08-30 10:27 UTC, kudoh commented on src/posts/sss/rds-major-ver-up.md
> +## STEP.1
STEP.1だけでなく、セクションのタイトルも付けた方が内容が分かりやすくなるかなと思います。
以降の段落も同じです。

2023-08-30 10:27 UTC, kudoh commented on src/posts/sss/rds-major-ver-up.md
> +理由は単純で、SSSで踏み台サーバとして利用しているGuimove/bastionのLinuxサーバのパッケージツールが15系に対応していなかったためです。
`Guimove/bastion`といってピンとくる読者は少ないかと思います。
書く場合は内容を補足した方がいいかと思います。もしくは本題でないので、この部分は省略してもいいのかなと思ったりもします。

2023-08-30 10:32 UTC, kudoh commented on src/posts/sss/rds-major-ver-up.md
> +営業支援システム(Sales Support System、以下SSS)で実施したAmazon Aurora PostgreSQLのメジャーバージョンアップ手順について紹介します。
営業支援システムと言っても知らない読者がほとんどだと思います。
近藤真さんの説明記事のリンクを貼るなどして本題に入る前にシステムの紹介をしてはいかがでしょう？

2023-08-31 00:39 UTC, kudoh approved these changes
👍

2023-09-01 03:54 UTC, kondoumh commented
マージします。

2023-09-01 03:54 UTC, merged